# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'removeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_removeDialog(object):
    def setupUi(self, removeDialog):
        removeDialog.setObjectName("removeDialog")
        removeDialog.resize(477, 374)
        self.gridLayout = QtWidgets.QGridLayout(removeDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(removeDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.fileList = QtWidgets.QListWidget(removeDialog)
        self.fileList.setAlternatingRowColors(True)
        self.fileList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.fileList.setObjectName("fileList")
        self.gridLayout.addWidget(self.fileList, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(removeDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(removeDialog)
        self.buttonBox.accepted.connect(removeDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(removeDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(removeDialog)

    def retranslateUi(self, removeDialog):
        _translate = QtCore.QCoreApplication.translate
        removeDialog.setWindowTitle(_translate("removeDialog", "Remove Items"))
        self.label.setText(_translate("removeDialog", "Select Items to Remove"))
